//ALERT
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

//BLOG
export const ADD_BODY_CLASSNAME = 'ADD_BODY_CLASSNAME'
export const REMOVE_BODY_CLASSNAME = 'REMOVE_BODY_CLASSNAME'
export const SHOW_SEARCH_FORM = 'SHOW_SEARCH_FORM'
export const FETCH_BLOGS = 'FETCH_BLOGS'
export const FETCH_COMMENT = 'FETCH_COMMENT'
export const SET_ERROR = 'SET_ERROR'
export const SET_SUCCESS = 'SET_SUCCESS'
export const GET_BLOGS = 'GET_BLOGS'
export const BLOG_ERROR = 'BLOG_ERROR'

//COMMENT
export const GET_COMMENT = 'GET_COMMENT'
export const ADD_COMMENT = 'ADD_COMMENT'
export const COMMENT_ERROR = 'COMMENT_ERROR'
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS'
export const REMOVE_ERROR = 'REMOVE_ERROR'
export const REMOVE_COMMENT_WARNING = 'REMOVE_COMMENT_WARNING'

